### PR TITLE
or_else calls func with error state

### PR DESCRIPTION
**Pull request by rollbear**
Takes care of issue #21

### CODE REVIEW

**Comment by rollbear** [comment]
I am very confused by the C++11 failures. Or rather, I understand them perfectly well, but not really how my change can have caused them...

Should I attempt to fix?

**Comment by TartanLlama** [comment]
I think guarding the `const&&` overload with `#ifndef TL_EXPECTED_NO_CONSTRR` and changing `constexpr` on `or_else_impl` to `TL_EXPECTED_11_CONSTEXPR` would fix it.

**Comment by TartanLlama** [comment]
I hate compilers.

**Comment by rollbear** [comment]
Yes, I'm working on it. Copying the same construction as is used for `and_then`, I think.

**Comment by rollbear** [comment]
You are brave to support g++-4.8. That is ancient history.

**Comment by TartanLlama** [comment]
Haha, yeah, I regret it sometimes.

**Comment by TartanLlama** [comment]
Changes look good to me, thanks very much!

**Pull request merged**
