### PR TITLE
Modify Conanfile to package expected as a header-only library

### PR DESCRIPTION
**Pull request by yipdw**
Before describing the PR, I'd like to offer an alternative outcome for this PR: deletion of the Conanfile.

Since submitting the Conanfile, I've had some time to reflect on what C++ packaging ought to be like, and I'm coming around to [Robert Schumacher's thesis on packaging](https://www.youtube.com/watch?v=sBP17HQAQjk), e.g. that libraries should be packageable but not _packaged_.   In line with that, I'd be happy to maintain a `conan-expected` repository elsewhere.

That said, onto the PR:

----

Previously, the Conanfile had the package ID depend on settings like the
target architecture and compiler.  expected's test executable depends on
this information, but the library itself does not.

This commit modifies the Conanfile as follows:

- eliminates tests (not needed if we just want the library)
- eliminates the influence of build settings on the package ID

### CODE REVIEW

**Comment by TartanLlama** [comment]
I think having an external package sounds like a great idea and thanks very much for offering to maintain one. I'm currently redoing the CMake to make the library more in line with what people expect, so you might want to hold off until it's merged: https://github.com/TartanLlama/expected/pull/55

**Comment by yipdw** [comment]
Sounds good :+1: I'll keep an eye on that PR.

**Comment by yipdw** [comment]
Thanks for 1.0! :tada: 

I've extracted the Conan recipe from this repository into https://github.com/yipdw/conan-tl-expected, and have updated it to use the CMake rules for build and packaging.  I've also taken advantage of the 0.4 -> 1.0 major version bump to rename the Conan package from `expected` to `tl-expected`; please let me know if you'd like this changed.

I'm okay with resolving this PR by removing the Conan material from this repository, maybe also with adding a reference to the new Conan recipe for anyone who might be using it from this repo.

**Comment by TartanLlama** [comment]
Thank you!

**Pull request merged**
